/* STATS */
// LABELS
export const GET_LABELS = "GET_LABELS";
export const GET_LABELS_SUCCESS = "GET_LABELS_SUCCESS";
export const GET_LABELS_ERROR = "GET_LABELS_ERROR";

// PROPERTIES
export const GET_PROPERTIES = "GET_PROPERTIES";
export const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS";
export const GET_PROPERTIES_ERROR = "GET_PROPERTIES_ERROR";

// OBJECTS
export const GET_OBJECTS = "GET_OBJECTS";
export const GET_OBJECTS_SUCCESS = "GET_OBJECTS_SUCCESS";
export const GET_OBJECTS_ERROR = "GET_OBJECTS_ERROR";

// TEXTS
export const GET_TEXTS = "GET_TEXTS";
export const GET_TEXTS_SUCCESS = "GET_TEXTS_SUCCESS";
export const GET_TEXTS_ERROR = "GET_TEXTS_ERROR";

// PHOTO SCORE
export const GET_PHOTO_SCORE = "GET_PHOTO_SCORE";
export const GET_PHOTO_SCORE_SUCCESS = "GET_PHOTO_SCORE_SUCCESS";
export const GET_PHOTO_SCORE_ERROR = "GET_PHOTO_SCORE_ERROR";

// FACES
export const GET_FACES = "GET_FACES";
export const GET_FACES_SUCCESS = "GET_FACES_SUCCESS";
export const GET_FACES_ERROR = "GET_FACES_ERROR";

// FACES
export const GET_EXIF = "GET_EXIF";
export const GET_EXIF_SUCCESS = "GET_EXIF_SUCCESS";
export const GET_EXIF_ERROR = "GET_EXIF_ERROR";

// LOADING
export const LOADING = "LOADING";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_ERROR = "GET_FACES_ERROR";

export * from "./stats/actions";
